# Generated by Django 5.1.2 on 2024-11-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_list',
            old_name='task_status',
            new_name='completed',
        ),
    ]
